spring.application.name=assessment4

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/insurance
spring.datasource.username=root
spring.datasource.password=Varshith@100

# JPA configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8080